### ISSUE TITLE
Feature Suggestion : biome toggler in config file

### ISSUE THREAD

**Issue by troyere** [CrypticVerse/BetterBiomes#15]
**Is your feature request related to a problem? Please describe.**
When polishing a seed with a specific theme, avoiding some biomes might be necessary to keep minimum harmony with the choosen theme. Or more fundamentally, some people might not like certain biomes, while they love others of the same mod.

**Describe the solution you'd like**
Just like in biome o plenty, a config file of booleans in order to enable/disable any biome would be great 😊

**Describe alternatives you've considered**
Sadly I have no alternative solutions in mind 😅 the mod biome replacer does not work all the time as it is explained in its description.

**Additional context**
An example of the biome o plenty toggler : 
![image](https://github.com/user-attachments/assets/b137fe1f-c0b4-4150-8017-5a1155a584db)

**Comment by CrypticVerse** [comment]
I honestly think this is a great idea! Allowing more users to customize what biomes generate in their world is a big step towards full customization of better biomes. We could also allow certain structures to be generated through config file too.

**Comment by CrypticVerse** [comment]
Hi! I am so sorry, but this mod is being archived. I just haven't had time to work on it, and Mocha (my partner) just left the project (due to reasons coming in a blog on bookkeepersmc.github.io). Again, I am so sorry to close this issue due to archives, it really was a great idea! As an alternative to this great suggestion, I am currently working on a public mod-loader and API, and would love to build in this idea into the biome API.

Thanks for understanding,
Cryptic.

**Comment by CrypticVerse** [comment]
If you have any other suggestions, feel free to drop a discussion on @BookkeepersMC or email me at: crypticversemc@gmail.com
